import Head from "next/head";
import Image from "next/image";
import Banner from "../Components/Banner";
import Card from "../Components/Card";
import styles from "../styles/Home.module.css";

import coffeeStore from "../lib/coffeeStore";
import useTrackLocation from "../hooks/use-track-location";


export async function getStaticProps(context) {
  const CoffeeStoreData = await coffeeStore();
  return {
    props: {
      coffeeStoreData: CoffeeStoreData,
    }, // will be passed to the page component as props
  };
}

export default function Home({ coffeeStoreData }) {
  const { handleLocation, LatLong, LocationErrorMsg } = useTrackLocation();
  handleLocation();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <div className={styles.bannerImage}>
        <Image src="/static/hero-image.png" height={380} width={1024} />
      </div>
      <div><h2>Stores Near You</h2></div>
      <div className={styles.cardList}>
        {coffeeStoreData.map((data) => {
          return (
            <Card
              key={data.id}
              name={data.name}
              address={data.address}
              imgUrl={
                data.imgUrl}
              Url={data.id}
            />
          );
        })}
        {/* <Card
          key={ 1}
          name={"name"}
          address={ "address"}
          // imgUrl={
          //    "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
          // }
          imgUrl={
            "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
          }
          Url={1}
        /> */}
      </div>
    </div>
  );
}
