import Head from "next/head";
import Image from "next/image";
import Banner from "../Components/Banner";
import Card from "../Components/Card";
import styles from "../styles/Home.module.css";

import coffeeStore from "../lib/coffeeStore";

export async function getStaticProps(context) {
  const LatLong = "19.12,72.89";
  const limit = 9;
  const Query = "Coffee";
  const CoffeeStoreData = await coffeeStore(Query, LatLong, limit);
  return {
    props: {
      coffeeStoreData: CoffeeStoreData,
    }, // will be passed to the page component as props
  };
}

export default function Home( { coffeeStoreData } ) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <div className={styles.bannerImage}>
        <Image src="/static/hero-image.png" height={480} width={1200} />
      </div>
      <div className={styles.cardList}>
        {coffeeStoreData.map((data, i) => {
          return (
            <Card
              key={data.id || i}
              name={data.name|| "name"}
              address={data.address || "address"}
              // imgUrl={
              //    "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
              // }
              imgUrl={
                data.imgUrl || "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
              }
              Url={data.id|| i}
            />
          );
        })}
        {/* <Card
          key={ 1}
          name={"name"}
          address={ "address"}
          // imgUrl={
          //    "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
          // }
          imgUrl={
            "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
          }
          Url={1}
        /> */}
      </div>
    </div>
  );
}
