import Head from "next/head";
import Image from "next/image";
import Banner from "../Components/Banner";
import Card from "../Components/Card";
import styles from "../styles/Home.module.css";

import coffeeStore from "../lib/coffeeStore";
import CoffeeImages from "../lib/CoffeeImages";

export async function getStaticProps(context) {
  const LatLong = "19.12,72.89";
  const limit = 9;
  const Query = "Coffee";
  const CoffeeStoreData = await coffeeStore(Query, LatLong, limit);
  const ImageData = await CoffeeImages();
  return {
    props: {
      coffeeStoreData: CoffeeStoreData,
      coffeeStoreImage: ImageData,
    }, // will be passed to the page component as props
  };
}

export default function Home({ coffeeStoreData, coffeeStoreImage }) {
  const Images = coffeeStoreImage.map(images => {
      return images.urls.regular
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <div className={styles.bannerImage}>
        <Image src="/static/hero-image.png" height={480} width={1200} />
      </div>
      <div className={styles.cardList}>
        {coffeeStoreData.map((data, i) => {
          return (
            <Card
              key={data.fsq_id}
              name={data.name}
              address={data.location.formatted_address}
              imgUrl={
                Images[i]
              }
              Url={data.fsq_id}
            />
          );
        })}
      </div>
    </div>
  );
}
